# module name
name: 'dummy'

# module instances
modules:
  stem:
    type: 'res50_neck'
    cfg:
      res50_neck_cfg0: 0
      res50_neck_cfg1: 1
      res50_neck_cfg2: 2
  backbone:
  neck:
  head:
  loss:

# connections between instances
connections:
  - ['stem.o.x', 'backbone.i.x']
  - ['stem.o.y', 'backbone.i.y']
  - ['backbone.o.x', 'neck.i.x']
  - ['neck.o.x', 'head.i.x']
  - ['head.o.x', 'loss.i.x']

# parameter connections
parameters:
  - ['cfg0', 'stem.cfg0']
  - ['cfg1', 'stem.cfg1']

